#!/bin/bash
# Owner: ImmorTerm Memory
# ImmorTerm Memory: Post-Compact Context Recovery
# Event: SessionStart (matcher: "compact")
# Project: lonormaly-krispyai
#
# Reads the handoff note generated by the pre-compact hook and injects
# full context directly — task list, session summary, current plan,
# user messages, and pending decisions. Zero MCP calls needed.

STDIN_DATA=$(cat 2>/dev/null || echo '{}')

IFS='|' read -r SESSION_ID CWD_PATH < <(echo "$STDIN_DATA" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(data.get('session_id', ''), data.get('cwd', ''), sep='|')
except Exception:
    print('|')
" 2>/dev/null)
SESSION_ID="${SESSION_ID:-}"

HANDOFF_FILE="$HOME/.immorterm/handoff/immorterm-handoff-${SESSION_ID}.json"

if [ -n "$SESSION_ID" ] && [ -f "$HANDOFF_FILE" ]; then
  # ── Rich handoff injection ──────────────────────────────────────
  RECOVERY_OUTPUT=$(HANDOFF_PATH="$HANDOFF_FILE" HANDOFF_SID="$SESSION_ID" \
  python3 << 'RECOVERY_PYTHON'
import json, sys, os

handoff_path = os.environ["HANDOFF_PATH"]
session_id = os.environ["HANDOFF_SID"]

try:
    with open(handoff_path) as f:
        h = json.load(f)
except Exception as e:
    print(f"Error reading handoff: {e}", file=sys.stderr)
    sys.exit(1)

out = []
out.append("SessionStart:compact hook success: <immorterm-compact-recovery>")
out.append("")
out.append("## Context Was Compacted — Full Handoff Loaded")
out.append("")
out.append(f"**Your session UUID**: \`{session_id}\`")
out.append("")

# ── Session Summary ──
summary = h.get("session_summary", "")
if summary:
    out.append("### Session Summary")
    out.append("")
    out.append(summary)
    out.append("")

# ── Task List ──
tasks = h.get("tasks", [])
if tasks:
    in_progress = [t for t in tasks if t.get("status") == "in_progress"]
    pending = [t for t in tasks if t.get("status") == "pending"]
    completed = [t for t in tasks if t.get("status") == "completed"]
    recreatable = in_progress + pending

    out.append("### Task List (reconstructed from pre-compact state)")
    out.append("")

    if in_progress:
        out.append("**In Progress:**")
        for t in in_progress:
            out.append(f"- [ ] #{t['id']} {t['subject']}")
            if t.get("description"):
                out.append(f"  - {t['description'][:200]}")
        out.append("")

    if pending:
        out.append("**Pending:**")
        for t in pending:
            out.append(f"- [ ] #{t['id']} {t['subject']}")
            if t.get("description"):
                out.append(f"  - {t['description'][:200]}")
        out.append("")

    if completed:
        out.append("**Completed:**")
        for t in completed:
            out.append(f"- [x] ~~#{t['id']} {t['subject']}~~")
        out.append("")

    if recreatable:
        out.append("<!-- TASK RECONSTRUCTION DATA (machine-readable) -->")
        out.append("<tasks-to-recreate>")
        out.append(json.dumps(recreatable))
        out.append("</tasks-to-recreate>")
        out.append("")
        out.append("**IMPORTANT**: Call \`TaskList\` first. If tasks already exist (survived compaction), do NOT recreate them — the list above is just for reference. Only call \`TaskCreate\` if \`TaskList\` returns an empty list, then use the \`<tasks-to-recreate>\` data above with the \`subject\`, \`description\`, and \`activeForm\` fields, followed by \`TaskUpdate\` to set the correct \`status\` for each.")
        out.append("")
    else:
        out.append("All tasks were completed before compaction. No reconstruction needed.")
        out.append("")
else:
    out.append("### Task List")
    out.append("")
    out.append("No tasks were active before compaction.")
    out.append("")

# ── Current Plan ──
plan = h.get("plan", "")
if plan:
    out.append("### Current Working Plan")
    out.append("")
    plan_display = plan[:2000]
    if len(plan) > 2000:
        plan_display += "\n\n[... truncated — use \`search_memory(query=\"plan\")\` for full text ...]"
    out.append("\`\`\`")
    out.append(plan_display)
    out.append("\`\`\`")
    out.append("")

# ── Last User Requests ──
user_msgs = h.get("user_messages", [])
if user_msgs:
    out.append("### Last User Requests")
    out.append("")
    for i, msg in enumerate(user_msgs, 1):
        display = msg[:200]
        if len(msg) > 200:
            display += "..."
        out.append(f"{i}. {display}")
    out.append("")

# ── Last Conversation Exchange (from ai.jsonl) ──
try:
    import glob as _glob
    iid = os.environ.get("IMMORTERM_WINDOW_ID", "")
    if iid:
        log_dir = None
        # Find log dir from registry or by globbing
        for reg_path in [os.path.join(os.getcwd(), '.immorterm', 'registry.json'),
                         os.path.join(os.path.expanduser('~'), '.immorterm', 'registry.json')]:
            try:
                with open(reg_path) as rf:
                    reg = json.load(rf)
                for s in reg.get('sessions', []):
                    if s.get('window_id') == iid:
                        log_dir = s.get('structured_log_dir')
                        break
                if log_dir:
                    break
            except Exception:
                continue
        if not log_dir:
            for base in [os.path.join(os.getcwd(), '.immorterm', 'terminals', 'logs'),
                         os.path.join(os.path.expanduser('~'), '.immorterm', 'terminals', 'logs')]:
                matches = _glob.glob(os.path.join(base, f'*_{iid}'))
                if matches:
                    log_dir = matches[0]
                    break
        if log_dir:
            ai_path = os.path.join(log_dir, 'ai.jsonl')
            if os.path.exists(ai_path):
                with open(ai_path, 'rb') as af:
                    try:
                        af.seek(-200_000, 2)
                        af.readline()
                    except OSError:
                        af.seek(0)
                    lines = af.readlines()
                turns = []
                for line in lines:
                    try:
                        entry = json.loads(line)
                        if entry.get('event') != 'turn':
                            continue
                        role = entry.get('role', 'assistant')
                        content = entry.get('content', '').strip()
                        if content:
                            turns.append((role, content))
                    except Exception:
                        continue
                last_user = last_asst = None
                for role, content in reversed(turns):
                    if role == 'user' and not last_user:
                        last_user = content[:2000]
                    elif role == 'assistant' and not last_asst:
                        last_asst = content[:2000]
                    if last_user and last_asst:
                        break
                if last_user or last_asst:
                    out.append("### Last Conversation Exchange")
                    out.append("")
                    if last_user:
                        out.append(f"**Last user message:**\n{last_user}")
                        out.append("")
                    if last_asst:
                        out.append(f"**Last assistant response:**\n{last_asst}")
                        out.append("")
except Exception:
    pass

# ── Pending Decisions ──
decisions = h.get("pending_decisions", [])
if decisions:
    this_session = [d for d in decisions if d.get("this_session")]
    other_sessions = [d for d in decisions if not d.get("this_session")]

    out.append("### Pending Decisions")
    out.append("")

    if this_session:
        out.append("**This session:**")
        for d in this_session:
            out.append(f"- {d['text'][:200]}")
        out.append("")

    if other_sessions:
        out.append(f"**From other sessions** ({len(other_sessions)} decision(s)):")
        for d in other_sessions[:5]:
            out.append(f"- {d['text'][:150]}")
        if len(other_sessions) > 5:
            out.append(f"- ... and {len(other_sessions) - 5} more")
        out.append("")

# ── Next Steps ──
out.append("### Next Steps")
out.append("")
out.append("1. **Resume your work** — the context above shows exactly where you were")
out.append("2. **Use \`search_memory(query=\"...\")\` if you need details** on any specific topic")
out.append("3. The JSONL transcript is intact — all conversation history is preserved")
out.append("")
out.append("</immorterm-compact-recovery>")

print("\n".join(out))
RECOVERY_PYTHON
  )

  # Clean up handoff file (consumed)
  rm -f "$HANDOFF_FILE" 2>/dev/null

  if [ -n "$RECOVERY_OUTPUT" ]; then
    echo "$RECOVERY_OUTPUT"
    exit 0
  fi
fi

# ── Fallback: no handoff file — fetch summary from REST API ───────
SESSION_SUMMARY=""
if [ -n "$SESSION_ID" ]; then
  SESSION_SUMMARY=$(_IM_URL="http://127.0.0.1:${IMMORTERM_MEMORY_PORT:-8765}" _IM_PID="${IMMORTERM_PROJECT_ID:-lonormaly-krispyai}" \
    _IM_SID="$SESSION_ID" python3 -c "
import os, json, urllib.request

url = os.environ['_IM_URL']
pid = os.environ['_IM_PID']
sid = os.environ['_IM_SID']

def get_text(m):
    return m.get('content', m.get('memory', m.get('text', m.get('data', ''))))

# Try 1: checkpoint file -> memory ID -> fetch text
try:
    cp_path = os.path.expanduser('~/.immorterm/digest-checkpoints.json')
    with open(cp_path) as f:
        cp = json.load(f)
    for fpath, fdata in cp.get('files', {}).items():
        if sid in fpath:
            mid = fdata.get('summary_memory_id', '')
            if mid:
                req = urllib.request.Request(f'{url}/api/v1/memories/{mid}')
                with urllib.request.urlopen(req, timeout=3) as resp:
                    text = get_text(json.loads(resp.read()))
                    if text:
                        print(text)
                        exit()
            break
except Exception:
    pass

# Try 2: lookup-by-meta endpoint (works with both Rust and Docker API)
try:
    import urllib.parse
    params = urllib.parse.urlencode({
        'user_id': pid, 'memory_type': 'session_summary', 'session_id': sid
    })
    req = urllib.request.Request(f'{url}/api/v1/memories/lookup-by-meta?{params}')
    with urllib.request.urlopen(req, timeout=3) as resp:
        data = json.loads(resp.read())
        mems = data.get('memories', [])
        if mems:
            text = get_text(mems[0])
            if text:
                print(text)
                exit()
        elif data.get('memory_id'):
            mid = data['memory_id']
            req2 = urllib.request.Request(f'{url}/api/v1/memories/{mid}')
            with urllib.request.urlopen(req2, timeout=3) as resp2:
                text = get_text(json.loads(resp2.read()))
                if text:
                    print(text)
                    exit()
except Exception:
    pass
" 2>/dev/null)
fi

RECOVERY="SessionStart:compact hook success: <immorterm-compact-recovery>"
RECOVERY+=$'\n'"Context was compacted."
RECOVERY+=$'\n'
RECOVERY+="immorterm_id: ${IMMORTERM_WINDOW_ID:-}"
RECOVERY+=$'\n'"session_id: ${SESSION_ID}"
RECOVERY+=$'\n'
if [ -n "$SESSION_SUMMARY" ]; then
  RECOVERY+=$'\n'"### Session Summary"$'\n'
  RECOVERY+="$SESSION_SUMMARY"$'\n'
fi

# ── Fetch last conversation turns from ai.jsonl ─────────────────
LAST_TURNS=""
if [ -n "$IMMORTERM_WINDOW_ID" ]; then
  LAST_TURNS=$(_IM_ID="$IMMORTERM_WINDOW_ID" python3 -c "
import os, json, glob

iid = os.environ['_IM_ID']
home = os.path.expanduser('~')

log_dir = None
for reg_path in [os.path.join(os.getcwd(), '.immorterm', 'registry.json'),
                 os.path.join(home, '.immorterm', 'registry.json')]:
    try:
        with open(reg_path) as f:
            reg = json.load(f)
        for s in reg.get('sessions', []):
            if s.get('window_id') == iid:
                log_dir = s.get('structured_log_dir')
                break
        if log_dir:
            break
    except Exception:
        continue

if not log_dir:
    for base in [os.path.join(os.getcwd(), '.immorterm', 'terminals', 'logs'),
                 os.path.join(home, '.immorterm', 'terminals', 'logs')]:
        matches = glob.glob(os.path.join(base, f'*_{iid}'))
        if matches:
            log_dir = matches[0]
            break

if not log_dir:
    exit()

ai_path = os.path.join(log_dir, 'ai.jsonl')
if not os.path.exists(ai_path):
    exit()

with open(ai_path, 'rb') as f:
    try:
        f.seek(-200_000, 2)
        f.readline()
    except OSError:
        f.seek(0)
    lines = f.readlines()

turns = []
for line in lines:
    try:
        entry = json.loads(line)
        if entry.get('event') != 'turn':
            continue
        role = entry.get('role', 'assistant')
        content = entry.get('content', '').strip()
        if content:
            turns.append((role, content))
    except Exception:
        continue

if not turns:
    exit()

last_user = last_asst = None
for role, content in reversed(turns):
    if role == 'user' and not last_user:
        last_user = content[:2000]
    elif role == 'assistant' and not last_asst:
        last_asst = content[:2000]
    if last_user and last_asst:
        break

output = []
if last_user:
    output.append(f'**Last user message:**
{last_user}')
if last_asst:
    output.append(f'**Last assistant response:**
{last_asst}')
if output:
    print('

'.join(output))
" 2>/dev/null)
fi

if [ -n "$LAST_TURNS" ]; then
  RECOVERY+=$'\n'"### Last Conversation Exchange"$'\n'
  RECOVERY+="$LAST_TURNS"$'\n'
fi

RECOVERY+=$'\n'"To resume your work:"
RECOVERY+=$'\n'"1. get_session_context(session_id='${SESSION_ID}') — load session summary + facts"
RECOVERY+=$'\n'"2. get_plan(session_id='${SESSION_ID}') — check for active plan"
RECOVERY+=$'\n'"3. TaskList — check current tasks"
RECOVERY+=$'\n'"</immorterm-compact-recovery>"
echo "$RECOVERY"
